### ISSUE TITLE
Translator Bot

### ISSUE THREAD

**Issue by RobHowdle** [Droid-Builder-Web-Team/discord_bot#19]
Nicknamed C3PO, need to use a translator API to translate text to other languages - Rob

**Comment by dpoulson** [comment]
This is likely to be a totally different bot, rather than an extension of this one. Wouldn't be able to call it a different name I think.

**Comment by RobHowdle** [comment]
> 
> 
> This is likely to be a totally different bot, rather than an extension of this one. Wouldn't be able to call it a different name I think.

Yeah most likely, wasn't sure whether to open a new thing for the C-3PO bot but to be honest until that is sorted and the backlog is cleared it's not overly important :D
